Repository appuio/component-openshift4-operators, pull requests merged in 2023-03, with the labels that each got.

#22 Allow use of custom namespace names for this component
  .github/workflows/test.yaml
  Makefile.vars.mk
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
  lib/openshift4-operators.libsonnet
  tests/golden/openshift-operators-custom/openshift-operators-custom/apps/openshift4-operators.yaml
  tests/golden/openshift-operators-custom/openshift-operators-custom/openshift4-operators/monitoring.yaml
  tests/golden/openshift-operators-custom/openshift-operators-custom/openshift4-operators/openshift-operators-custom.yaml
  tests/openshift-operators-custom.yml
Labels: enhancement

#25 Remove support for component-prometheus based monitoring
  class/defaults.yml
  component/main.jsonnet
  component/monitoring.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  jsonnetfile.json
  tests/golden/openshift-operators-custom/openshift-operators-custom/openshift4-operators/monitoring.yaml
  tests/golden/openshift-operators-redhat/openshift-operators-redhat/openshift4-operators/monitoring.yaml
  tests/golden/openshift-operators/openshift-operators/openshift4-operators/monitoring.yaml
  tests/openshift-operators-custom.yml
  tests/openshift-operators-redhat.yml
  tests/openshift-operators.yml
Labels: change

#26 Always use `openshift-operators` as default namespace in ArgoCD app
  component/app.jsonnet
Labels: bug

#27 Don't take over ownership of OpenShift-managed namespace `openshift-operators`
  component/main.jsonnet
  tests/golden/openshift-operators/openshift-operators/openshift4-operators/openshift-operators.yaml
  tests/openshift-operators.yml
Labels: bug

#28 Add new component parameter for managing a subscription
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/operator-subscription/operator-subscription/apps/openshift4-operators.yaml
  tests/golden/operator-subscription/operator-subscription/openshift4-operators/operator-subscription.yaml
  tests/operator-subscription.yml
Labels: enhancement

#29 Add Aldebaran Tech as CodeOwners
  CODEOWNERS
Labels: documentation
